language: python
env:
  - VERSION=${TRAVIS_TAG:-vdev}
install:
  - pip install -U platformio
script:
  - export PLATFORMIO_BUILD_FLAGS="-D'VERSION=\"${VERSION}\"'" -DLED_STRIP_COUNT=144 -DLED_STRIP_TYPE=4
  - pio run -e release
  - mv .pio/build/release/firmware.bin twr-radio-power-controller-rgbw144-${VERSION}.bin

  - export PLATFORMIO_BUILD_FLAGS="-D'VERSION=\"${VERSION}\"'" -DLED_STRIP_COUNT=72 -DLED_STRIP_TYPE=4
  - pio run -e release
  - mv .pio/build/release/firmware.bin twr-radio-power-controller-rgbw72-${VERSION}.bin

  - export PLATFORMIO_BUILD_FLAGS="-D'VERSION=\"${VERSION}\"'" -DLED_STRIP_COUNT=36 -DLED_STRIP_TYPE=4
  - pio run -e release
  - mv .pio/build/release/firmware.bin twr-radio-power-controller-rgbw36-${VERSION}.bin

  - export PLATFORMIO_BUILD_FLAGS="-D'VERSION=\"${VERSION}\"'" -DLED_STRIP_COUNT=150 -DLED_STRIP_TYPE=3
  - pio run -e release
  - mv .pio/build/release/firmware.bin twr-radio-power-controller-rgb150-${VERSION}.bin

  - ls -lha
deploy:
  skip_cleanup: true
  file_glob: true
  file: ./*.bin
  api_key: ${GITHUB_KEY}
  provider: releases
  overwrite: true
  on:
    tags: true
