article: https://www.bigclown.com/doc/projects/radio-smart-led-strip/
video: https://youtu.be/idxAoc2q6O0
images:
  - title:
    url: https://github.com/hardwario/website/blob/master/static/kits-images/co2-monitor/main.png
assembly:
  - name: HARDWARIO Cover Module
  - name: HARDWARIO Core Module
  - name: HARDWARIO Power Module
